# Your welcome to the jungle username

welcome_to_the_jungle_username: ""

# Your welcome to the jungle password

welcome_to_the_jungle_password: ""

# Job keyword list

job_keyword_list:
  - "developpeur python"
  - "ingénieur logiciel python"
  - "développeur backend"
  - "développeur fullstack"
  - "développeur frondend"
  - "développeur embarqué"
  

# If is_internship is set to false the bot will look for permanent contract otherwise he will search for internship

is_internship: False

# If sort_by_date is set to false the bot will look for jobs by relevance and not by date

sort_by_date: False

# number_of_page_to_search is equal to the number the bot will go through for each keyword it can be 1, 4 or even 21

number_of_page_to_search: 5

# The maximum number of offer you want to go through

maximum_number_of_offer: 25

# Where you want to search jobs

where_is_the_job: Île-de-France

# If those words are in the question of the offer the bot won't apply

forbiden_words_job_offer_question:
  - "devops"

# If those words are in the text of the offer the bot won't apply

forbiden_words_job_offer_text:

# Your current post

current_post: "ingénieur logiciel"

# Language needed for cover letter generation for chatgpt

language: "french"

# the lenght of the cover letter short , normal , long ...

covert_letter_lenght: very short