# Your welcome to the jungle username

welcome_to_the_jungle_username: ""

# Your welcome to the jungle password

welcome_to_the_jungle_password: ""

# Job keyword list (terms used to find / filter job offers)

job_keyword_list:
  - "developpeur python"
  - "ingénieur logiciel python"
  - "développeur backend"
  - "développeur frontend"
  - "développeur fullstack"
  

# If is_internship is set to false the bot will look for permanent contract otherwise he will search for internship

is_internship: False

# If sort_by_date is set to false the bot will look for jobs by relevance and not by date

sort_by_date: False

# number_of_page_to_search is equal to the number the bot will go through for each keyword it can be 1, 4 or even 21

number_of_page_to_search: 5

# The maximum number of offer you want to go through

maximum_number_of_offer: 5

# Town of the country where you want to search jobs put "anywhere" to apply to any town of your country

where_is_the_job: 
  - "paris"

# Country of the job

country_of_the_job: "France"

# If those words are in the question of the offer the bot won't apply

forbiden_words_job_offer_question:
  - "devopops"

# If those words are in the text of the offer the bot won't apply

forbiden_words_job_offer_text:
  - "java"

# Your current post

current_post: "ingénieur logiciel"

# Language needed for cover letter generation for chatgpt

language: "french"

# the lenght of the cover letter short , normal , long ...

covert_letter_lenght: very short

# If this is set to true the bot won't apply to an offer where a question is needed

skip_question: False

# If this is set to true the bot won't apply to an offer where a cover letter is needed

skip_cover_letter: False

# If print error is set to True the bot will print all the error that happend

print_error: False

# If this is set to False the bot will only send job url to discord and won't apply

apply: True

# If this is set to true the bot will only apply to job that got job_keyword_list inside the job offer name

apply_to_offer_who_have_job_keyword_list_element_in_their_name: False

# If this is set to True the bot won't apply to the job offer and it will send a discord message with the cover letter and the url of the job offer so you can see how the cover letter look
print_cover_letter: False